openapi: 3.0.0
info:
  title: McPay
  version: '1'
  description: McPay OAauth and McPayments docs
  termsOfService: ''
servers:
  - url: 'https://mcpay.io'
    description: Production
  - description: Development
    url: 'https://mp-stage.mediacube.dev'
paths:
  /oauth/token:
    post:
      summary: Token
      operationId: post-oauth-token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token_type:
                    type: string
                    enum:
                      - bearer
                  expires_in:
                    type: string
                  access_token:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
                  error_message:
                    type: string
                required:
                  - error
                  - error_description
                  - error_message
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                client_id:
                  type: string
                client_secret:
                  type: string
                code:
                  type: string
                redirect_uri:
                  type: string
                  format: uri
            examples:
              authorization_code:
                value:
                  grant_type: authorization_code
                  client_id: '1'
                  client_secret: secret
                  code: hjgsfugdskhgvklundfluvhdfnlvhls
                  redirect_url: 'https://yourapp.com/endpoint'
              partner:
                value:
                  grant_type: partner
                  client_id: '1'
                  client_secret: secret
        description: ''
      tags:
        - OAuth
  /oauth/user:
    get:
      summary: User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  email:
                    type: string
                  first_name:
                    type: string
                  last_name:
                    type: string
                  lang:
                    type: string
                  wallet:
                    type: string
                    description: |-
                      Default wallet account number.
                      > The default wallet corresponds to the wallet with **USD** currency and **cyprus** region
                    deprecated: true
                    example: '1111222233334444'
                  wallets:
                    x-stoplight:
                      id: eivq9dww2cql7
                    type: array
                    items:
                      $ref: '#/components/schemas/Wallet'
                  kyc_status:
                    type: number
                  is_confirmed:
                    type: boolean
                    description: Mail confirmation status
                  is_company:
                    type: boolean
                    description: Indicates whether the user represents a company (true) or an individual (false)
                  channels:
                    type: array
                    items: {}
                  created_at:
                    type: string
                  country:
                    $ref: '#/components/schemas/Country'
      operationId: get-oauth-user
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
      security:
        - Auth code: []
      tags:
        - OAuth
  /oauth/user/balance:
    get:
      summary: Balance Scope
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    x-stoplight:
                      id: wu721zh81bwkc
                    example: 1
                  balance:
                    type: string
                    description: Total balance (real_balance + credit_balance)
                    example: '30'
                  real_balance:
                    type: string
                    description: Balance of funds
                    example: '20'
                  credit_balance:
                    type: string
                    description: Balance of expresses
                    example: '10'
                  wallet:
                    $ref: '#/components/schemas/Wallet'
      operationId: get-oauth-user-balance
      description: |-
        Retrieving the user's wallet balance.
        If the **wallet** parameter is not provided, the default wallet is used.

        > The default wallet corresponds to the wallet with **USD** currency and **cyprus** region
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
        - schema:
            type: string
            example: '1111222233334444'
          in: query
          allowEmptyValue: true
          name: wallet
          description: Account wallet number
      security:
        - Auth code: []
      tags:
        - OAuth
    parameters: []
  /oauth/user/common:
    get:
      summary: Common Scope
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  common:
                    type: object
                    properties:
                      name:
                        type: string
                        description: first name + last name
                      email:
                        type: string
                        format: email
                      lang:
                        type: string
                        description: xx - Language format from ISO
                      is_confirmed:
                        type: boolean
                      avatar:
                        type: string
                        format: uri
                      wallet:
                        type: string
                        description: |-
                          Default wallet account number
                          > The default wallet corresponds to the wallet with **USD** currency and **cyprus** region
                        deprecated: true
                        example: '1111222233334444'
                      wallets:
                        type: array
                        x-stoplight:
                          id: 4jitlonbz5h8f
                        items:
                          $ref: '#/components/schemas/Wallet'
                      profile:
                        $ref: '#/components/schemas/Profile'
                      birthday:
                        type: string
                        format: date
                        example: '1995-07-13'
                      sex:
                        enum:
                          - male
                          - female
                          - other
                      country_id:
                        type: number
                      country:
                        $ref: '#/components/schemas/Country'
      operationId: get-oauth-user-common
      description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
      security:
        - Auth code: []
      tags:
        - OAuth
  /oauth/user/channels:
    get:
      summary: Channel Scope
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    youtube_id:
                      type: string
                    title:
                      type: string
                    published_at:
                      type: string
                      format: date
                      example: '2020-05-12'
                    views_count:
                      type: number
                    subscribers_count:
                      type: number
                    is_google_user_owner:
                      type: boolean
                    image:
                      type: string
      operationId: get-oauth-user-channels
      description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
      security:
        - Auth code: []
      tags:
        - OAuth
  /payments:
    post:
      summary: 'Create payout payment [v1]'
      operationId: post-payments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/McPaymentResource'
        '401':
          description: Your Access Token does not have access
        '422':
          description: Incorrect data
      description: |-
        The endpoint allows you to make payouts to users. Supports batch payout payments.

        Payouts are only allowed for **default** wallets. If you need to create a payment to other wallets, please use the [Create payout payment [v2]](reference/api.yaml/paths/~1payments~1v2~1payout/post)

        > The default wallet corresponds to the wallet with **USD** currency and **cyprus** region
      parameters:
        - schema:
            type: string
            example: Bearer <jwt-token>
          in: header
          name: Authorization
          required: true
          description: 'Token from partner grant '
        - schema:
            type: string
            example: application/json
          in: header
          required: true
          name: Content-Type
        - schema:
            type: string
            example: application/json
          in: header
          name: Accept
          required: true
      security:
        - Client credentials: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/McPaymentRequestV1'
            examples:
              Example 1:
                value:
                  request_id: unique-string-like-uuid
                  data:
                    - wallet: '00001111222233334444'
                      amount: '16.99'
                      description: Arrival from the referral system MediaCube Music
                      date: '2025-02-02'
                    - wallet: '11112222333344445555'
                      amount: '12'
                      description: Arrival from the referral system MediaCube Music
                      date: '2025-03-03'
      deprecated: true
      tags:
        - Payments V1
    get:
      summary: 'Get payment [v1]'
      operationId: get-payments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/McPaymentResource'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      description: ''
      parameters:
        - schema:
            type: string
            example: Bearer <jwt-token>
          in: header
          name: Authorization
          description: ''
          required: true
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-Type
          description: ''
          required: true
        - schema:
            type: string
            example: application/json
          in: header
          name: Accept
          required: true
      security:
        - Client credentials: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - request_id
              properties:
                request_id:
                  type: string
        description: ''
      tags:
        - Payments V1
      deprecated: true
    parameters: []
  /payments/debit:
    post:
      summary: Create debit payment
      operationId: post-payments-debit
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/McPaymentResource'
        '401':
          description: Your Access Token does not have access
        '422':
          description: Incorrect data
      description: The endpoint allows you to debit money from users wallets. Supports batch debiting of money
      parameters:
        - schema:
            type: string
            example: Bearer <jwt-token>
          in: header
          name: Authorization
          required: true
          description: 'Token from partner grant '
        - schema:
            type: string
            example: application/json
          in: header
          required: true
          name: Content-Type
        - schema:
            type: string
            example: application/json
          in: header
          name: Accept
          required: true
      tags:
        - Payments V1
      security:
        - Client credentials: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/McPaymentRequestV1'
            examples:
              Example 1:
                value:
                  request_id: stringstringstri
                  data:
                    - wallet: stringstringstri
                      amount: 0
                      description: string
    parameters: []
  /payments/v2/payout:
    post:
      summary: 'Create payout payment [v2]'
      tags:
        - Payments V2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/McPaymentResource'
        '401':
          description: Your Access Token does not have access
        '422':
          description: Incorrect data
      operationId: post-payments-v2-payout
      x-stoplight:
        id: rk861q33jlb3x
      description: The endpoint allows you to make payouts to users. Supports batch payout payments
      security:
        - Client credentials: []
      parameters:
        - schema:
            type: string
            example: Bearer <jwt-token>
          in: header
          name: Authorization
          description: 'Token from partner grant '
          required: true
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-Type
          required: true
        - schema:
            type: string
            example: application/json
          in: header
          name: Accept
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/McPaymentRequestV2'
            examples:
              Example 1:
                value:
                  request_id: unique-string-like-uuid
                  currency: USD
                  region: cyprus
                  data:
                    - wallet: '0000111122223333'
                      amount: '16.99'
                      description: Arrival from the referral system MediaCube Music
                      date: '2025-02-02'
                    - wallet: '0000111122223333'
                      amount: '12'
                      description: Arrival from the referral system MediaCube Music
                      date: '2025-03-03'
  /payments/v2/status:
    get:
      summary: 'Get payment [v2]'
      tags:
        - Payments V2
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      operationId: get-payments-v2-status
      x-stoplight:
        id: 4y2cy7vg3bjey
      security:
        - Client credentials: []
      parameters:
        - schema:
            type: string
            example: Bearer <jwt-token>
          in: header
          name: Authorization
          required: true
        - schema:
            type: string
            example: application/json
          in: header
          name: Content-Type
          required: true
        - schema:
            type: string
            example: application/json
          in: header
          name: Accept
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - request_id
              properties:
                request_id:
                  type: string
                  x-stoplight:
                    id: v707jmvr0xmpd
components:
  schemas:
    Country:
      title: Country
      type: object
      description: ''
      properties:
        id:
          type: number
        youtube_id:
          type: string
        code:
          type: string
        code_aplha3:
          type: string
        name:
          type: string
    Profile:
      title: Profile
      type: object
      properties:
        id:
          type: number
        user_id:
          type: number
        first_name:
          type: string
        last_name:
          type: string
        middle_name:
          type: string
        name:
          type: string
        region:
          type: string
        city:
          type: string
        address:
          type: string
        lang:
          type: string
        tax_id:
          type: string
        business_id:
          type: string
        is_real_address:
          type: boolean
        province:
          type: string
        real_province:
          type: string
        real_city:
          type: string
        real_adress:
          type: string
        real_postcode:
          type: string
        postcode:
          type: string
        company_name:
          type: string
    Wallet:
      title: Wallet
      x-stoplight:
        id: oi76a0mujbspf
      type: object
      properties:
        id:
          type: number
          x-stoplight:
            id: nsrsjjvi85h72
        region:
          x-stoplight:
            id: h2gas0yx8gmg8
          enum:
            - cyprus
            - canada
        currency:
          x-stoplight:
            id: gbwrw7458tfl0
          description: 'Currency [ISO-3 Format](https://www.iso.org/iso-4217-currency-codes.html)'
          enum:
            - USD
            - EUR
        number:
          type: string
          x-stoplight:
            id: ka7yije5hvkrc
          description: Wallet account number
          example: '1111222233334444'
    McPaymentRequestV1:
      title: McPaymentRequestV1
      x-stoplight:
        id: de2bq7lgdyjc8
      type: object
      x-examples:
        example-1:
          request_id: unique-string-like-uuid
          data:
            - wallet: '00001111222233334444'
              amount: '16.99'
              description: Arrival from the referral system MediaCube Music
              date: '2025-02-02'
            - wallet: '11112222333344445555'
              amount: '12'
              description: Arrival from the referral system MediaCube Music
              date: '2025-03-03'
      required:
        - request_id
        - data
      properties:
        request_id:
          type: string
          minLength: 16
          maxLength: 255
          description: 'Unique string like UUIDv4 '
        data:
          type: array
          items:
            type: object
            required:
              - wallet
              - amount
              - description
            properties:
              wallet:
                type: string
                description: McPay user's wallet
                minLength: 16
                maxLength: 16
              amount:
                type: number
                minimum: 0
                format: float
                exclusiveMaximum: false
                exclusiveMinimum: false
              description:
                type: string
                description: Payment description for user
                maxLength: 255
              date:
                type: string
                x-stoplight:
                  id: 03endfnm3fsml
                format: date
                description: 'Payment date. If not provided, the current date will be used.'
    McPaymentRequestV2:
      title: McPaymentRequestV2
      x-stoplight:
        id: qbxbl3102noi0
      type: object
      x-examples:
        Example 1:
          request_id: unique-string-like-uuid
          currency: USD
          region: cyprus
          data:
            - wallet: '00001111222233334444'
              amount: '16.99'
              description: Arrival from the referral system MediaCube Music
              date: '2025-02-02'
            - wallet: '11112222333344445555'
              amount: '12'
              description: Arrival from the referral system MediaCube Music
              date: '2025-03-03'
      required:
        - request_id
        - region
        - currency
        - data
      properties:
        request_id:
          type: string
          x-stoplight:
            id: o25ppsqypfrfk
          description: 'Unique string like UUIDv4 '
        region:
          x-stoplight:
            id: 3r1yvc4nv6waa
          enum:
            - cyprus
            - canada
            - kazakhstan
          description: Partner wallet account region
        currency:
          x-stoplight:
            id: zhj6917di8jqm
          description: 'Partner wallet account currency [ISO-3 Format](https://www.iso.org/iso-4217-currency-codes.html)'
          enum:
            - USD
            - EUR
        data:
          type: array
          x-stoplight:
            id: eg7xwmw9m9jxg
          items:
            x-stoplight:
              id: 6nzad5e2kocct
            type: object
            required:
              - wallet
              - amount
              - description
            properties:
              wallet:
                type: string
                x-stoplight:
                  id: 5vg4ii9jwjcuc
                description: McPay user's wallet
                minLength: 16
                maxLength: 16
              amount:
                type: number
                x-stoplight:
                  id: d4p1mhdiisltf
                format: float
                minimum: 0.01
              description:
                type: string
                x-stoplight:
                  id: z3or2kx7miw7b
                description: Payment description for user
                maxLength: 255
              date:
                type: string
                x-stoplight:
                  id: e2cph8ripv7l5
                format: date
                description: 'Payment date. If not provided, the current date will be used.'
    McPaymentResource:
      type: object
      x-examples:
        example-1:
          data:
            request_id: c02e79a2-d30c-46e3-b3dd-c0e6a987acf8
            status: 2
            err_msg: null
            transactions:
              - id: 1
                invoice_path: /api/transactions/1/invoice
              - id: 2
                invoice_path: /api/transactions/2/invoice
        example-2:
          data:
            request_id: string
            status: 3
            err_msg: 3000
            transactions: []
      title: McPaymentResource
      description: ''
      properties:
        data:
          type: object
          properties:
            request_id:
              type: string
            status:
              type: integer
            err_msg:
              type: integer
              nullable: true
            transactions:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  invoice_path:
                    type: string
                    description: Invoice path to PDF file
  securitySchemes:
    Client credentials:
      type: oauth2
      flows:
        clientCredentials:
          refreshUrl: 'https://mcpay,io/oauth/token'
          scopes: {}
          tokenUrl: 'https://mcpay,io/oauth/token'
      description: Access to McPayments API
    Auth code:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://mcpay,io/oauth/authorize'
          tokenUrl: 'https://mcpay,io/oauth/token'
          scopes:
            user.channels: Channels assigned to user
            user.common: 'User full english profile '
            user.balance: 'User balance '
          refreshUrl: 'https://mcpay,io/oauth/token'
      description: Basic auth_code flow with redirect and callback
  examples: {}
  requestBodies: {}
  responses: {}
tags:
  - name: OAuth
  - name: Payments
security: []
